<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.SAFUI.Testscripts.AddUsersTestscript" tests="4" time="0.003" ignored="0" failures="0" timestamp="26 May 2017 10:29:44 GMT" skipped="3" hostname="Bhushaya" errors="1">
  <testcase name="BaseTest" time="0.000" classname="com.SAFUI.Testscripts.AddUsersTestscript">
    <error type="java.lang.ArrayIndexOutOfBoundsException" message="1">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 1
	at com.SAFUI.Utils.ReadingProperties.getObjectLocator(ReadingProperties.java:39)
	at com.SAFUI.Pages.UsersPage.locatorsForUsers(UsersPage.java:34)
	at com.SAFUI.Pages.UsersPage.<init>(UsersPage.java:28)
	at com.SAFUI.Utils.TestTemplate.BaseTest(TestTemplate.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- BaseTest -->
  <testcase name="addNewUser" time="0.001" classname="com.SAFUI.Testscripts.AddUsersTestscript">
    <skipped/>
  </testcase> <!-- addNewUser -->
  <testcase name="addNewUser" time="0.001" classname="com.SAFUI.Testscripts.AddUsersTestscript">
    <skipped/>
  </testcase> <!-- addNewUser -->
  <testcase name="addNewUser" time="0.001" classname="com.SAFUI.Testscripts.AddUsersTestscript">
    <skipped/>
  </testcase> <!-- addNewUser -->
</testsuite> <!-- com.SAFUI.Testscripts.AddUsersTestscript -->
